### PR TITLE
Add command line option for stm32

### PR DESCRIPTION
**Pull request by goldarte**
Added mode for generating header that can be used in stm32 projects.

### CODE REVIEW

**Comment by rgujju** [comment]
Hi @goldarte 
Thanks for the PR. The code changes you have added are great. 
They seem generic for any microcontroller and not specific to stm32 right? Do you mind changing the `--stm32` part to something more generic? Or maybe even flipping it around and keeping it generic and then adding `--arduino` to add the arduino header part?

**Comment by rgujju** [comment]
Hi @goldarte 
Thanks for the PR. The code changes you have added are great. 
They seem generic for any microcontroller and not specific to stm32 right? Do you mind changing the `--stm32` part to something more generic? Or maybe even flipping it around and keeping it generic and then adding `--arduino` to add the arduino header part?

**Comment by goldarte** [comment]
Hi! I added option `--stm32` because I wanted to save the default behavior of your program.
The option called `--stm32` because I was trying to find solution to make hex arrays of jpeg pictures on Linux for using it with the code for stm32 controllers with no luck. But yes, this option makes generic code for almost any microcontroller. If you want, I can make behavior of this option (`--stm32`) default, and add `--arduino` option.

Waiting for your reply, @rgujju

**Comment by rgujju** [comment]
Hi @goldarte ,
Yes, go ahead with making `--stm32` as the default and adding `--arduino` option. 
Thanks for you help.

**Comment by goldarte** [comment]
Done

**Pull request merged**
